# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

defaultContentLanguage = "zh-cn"

enableRobotsTXT = true
paginate = 8
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/posts/:year/:month/:day/"
