languageCode = "zh-cn"
languageName = "Chinese-Simplified"
languageDirection = "Chinese-Simplified"
weight = 1

# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2006 January 2"
  description = "Shaocheng.Li's Blog"
  # mainSections = ["section1", "section2"]


[author]
  name = "Shaocheng.Li"
  image = "img/author.png"
  headline = "A man."
  bio = "A Linux software engineer."
  links = [
    { github = "https://github.com/exbob" },
  ]
